identity = "ace85b22f35ece5fd5ddcdbe02a5cc2637824b09"
resolved_url = "https://zml.ai/posts/index.xml"
title = "Posts on ZML - Model to Metal"
site_url = "https://zml.ai/posts/"
etag = 'W/"0e99d8c9d1d6cb9ffef2090acba98e01"'
body_hash = "c3d3384714ded26c7345615829042dcaab068d31"
