identity = "488df5cf40c5ee50bf9bc1bc721f172d767615ba"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCSULDz1yaHLVQWHpm4g_GHA"
title = "Monsieur Bidouille"
site_url = "https://www.youtube.com/channel/UCSULDz1yaHLVQWHpm4g_GHA"
body_hash = "635ef5bdf2b94c1abfa995fcc80e3d2efc626c66"
