identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dm1n3n9daxatcns-gzip"'
last_modified = "Sun, 11 Oct 2026 02:06:06 GMT"
body_hash = "84b5bdaae7cabd322dab77cfccc0d38bbc64a7a3"
