identity = "fa89c3714661dd428af5d15531129704bcceaa7b"
resolved_url = "https://martinfowler.com/feed.atom"
title = "Martin Fowler"
site_url = "https://martinfowler.com/"
etag = '"2cc11-65bae12f8db40"'
last_modified = "Thu, 17 Sep 2026 13:51:01 GMT"
body_hash = "987c863a3e632924a3d5f2dc83fbb62a7fcff570"
