# https://github.com/aymericbeaumet/aggr/blob/main/config.default.toml

[site]
title = "aymeric's"

[[networks]]
provider = "hackernews"

[[networks]]
provider = "reddit"

[[sources]]
category = "ai"
url = """
https://www.anthropic.com/news
https://cognition.com/blog
https://blog.google/innovation-and-ai/technology/ai/rss/
https://ai.meta.com/blog/
https://microsoft.ai/feed/?post_type=new
https://www.kimi.com/en/blog/
https://openai.com/news/rss.xml
https://qwen.ai/blog
https://x.ai/news
https://www.zhipuai.cn/en/news
https://zml.ai/posts/index.xml
"""

[[sources]]
category = "news"
url = """
https://hnrss.org/frontpage?points=100
"""

[[sources]]
category = "programming"
url = """
https://aymericbeaumet.com
https://martinfowler.com
https://simonwillison.net
https://www.youtube.com/@ThePrimeTimeagen
https://www.youtube.com/@TsodingDaily
"""

[[sources]]
category = "science"
url = """
https://www.youtube.com/@arstechnica
https://www.youtube.com/@HygieneMentale
https://www.youtube.com/@Julien_Bobroff
https://www.youtube.com/@monsieurbidouille
https://www.youtube.com/@numberphile
https://www.youtube.com/@PracticalEngineeringChannel
https://www.youtube.com/@ScienceEtonnante
https://www.youtube.com/@standupmaths
https://www.youtube.com/@TomScottGo
https://www.youtube.com/@veritasium
"""
