identity = "a618f03a5e84fc671e717663ebb730c6472954d7"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCaNlbnghtwlsGF-KzAFThqA"
title = "ScienceEtonnante"
site_url = "https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA"
body_hash = "a997160214c6820f53c36522533473a6ccadd0d7"
