identity = "0055d0d7d9782a9d30c5e9623b8950e280b85cfc"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCMFcMhePnH4onVHt2-ItPZw"
title = "Hygiène Mentale"
site_url = "https://www.youtube.com/channel/UCMFcMhePnH4onVHt2-ItPZw"
body_hash = "67afd7e6a721f28e17586829b7d191d66b53b0a6"
