identity = "d447efa9f362a8fc45b9b43de5fc19da4a02b6f1"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCCDU1fsmgvWljcW2aodfJsA"
title = "Ars Technica"
site_url = "https://www.youtube.com/channel/UCCDU1fsmgvWljcW2aodfJsA"
body_hash = "1ac093851ac5301afdebc708b7afe49ea6a9baa9"
