identity = "d447efa9f362a8fc45b9b43de5fc19da4a02b6f1"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCCDU1fsmgvWljcW2aodfJsA"
title = "Ars Technica"
site_url = "https://www.youtube.com/channel/UCCDU1fsmgvWljcW2aodfJsA"
body_hash = "a6c949980a45e51d381f9538d820e145088aac9d"
