identity = "d447efa9f362a8fc45b9b43de5fc19da4a02b6f1"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCCDU1fsmgvWljcW2aodfJsA"
title = "Ars Technica"
site_url = "https://www.youtube.com/channel/UCCDU1fsmgvWljcW2aodfJsA"
body_hash = "399b7be43d8b03615b16941669c1178479d773cf"
