identity = "1aa0f2d646643a9955c313c03e4990c87ee50489"
resolved_url = "https://registerspill.thorstenball.com/feed"
title = "Register Spill"
site_url = "https://registerspill.thorstenball.com/"
etag = 'W/"6950f-c+lSF8H3rF3EaRs0FlXd1nR7+Aw"'
body_hash = "73e95217c1f7ac5dc4691b341655ddd6747bf80c"
