identity = "ba7c57f6944bccf3ca7da7e6ff2845dd16aa9eaf"
resolved_url = "https://lucumr.pocoo.org/feed.atom"
title = "Armin Ronacher's Thoughts and Writings"
site_url = "https://lucumr.pocoo.org/"
etag = 'W/"6aaeceba-2acc0"'
last_modified = "Sat, 19 Sep 2026 18:04:42 GMT"
body_hash = "a36e7022973303331a506e081339311ffa29e999"
