identity = "79b32c4202bded4b55d8ae74bc41729d0a5b0811"
resolved_url = "https://www.anthropic.com/news"
title = 'Newsroom \ Anthropic'
site_url = "https://www.anthropic.com/"
body_hash = "9f2ba736536849ad4e67c10594248a8468ac8da7"
