identity = "79b32c4202bded4b55d8ae74bc41729d0a5b0811"
resolved_url = "https://www.anthropic.com/news"
title = 'Newsroom \ Anthropic'
site_url = "https://www.anthropic.com/"
body_hash = "6962471df88b021d321e076de864b5ea4a919533"
