url = "https://www.techmeme.com/feed.xml"
title = "Techmeme"
site_url = "https://www.techmeme.com/"
etag = 'W/"55b3-65a8259226f15"'
last_modified = "Wed, 02 Sep 2026 16:15:47 GMT"
body_hash = "9651283799324181522bea5741fc8f363a2cff42"
