url = "https://www.techmeme.com/feed.xml"
title = "Techmeme"
site_url = "https://www.techmeme.com/"
etag = 'W/"5257-65a87ba556923"'
last_modified = "Wed, 02 Sep 2026 22:40:53 GMT"
body_hash = "62ba17a906be295938bace04e10f66a5c49162f2"
