url = "https://www.techmeme.com/feed.xml"
title = "Techmeme"
site_url = "https://www.techmeme.com/"
etag = 'W/"56a1-65a8194984780"'
last_modified = "Wed, 02 Sep 2026 15:20:50 GMT"
body_hash = "66d0a71e1cb89dd7d43318337528d7560c5a755f"
