identity = "e57339d2da55f99410e3770305dae0de99354bcc"
resolved_url = "https://geohot.github.io//blog/feed.xml"
title = "the singularity is nearer"
site_url = "https://geohot.github.io//blog/"
etag = 'W/"6a838cc0-b683"'
last_modified = "Mon, 17 Aug 2026 22:35:44 GMT"
body_hash = "8adf86312bd7db427a52e2122783c685ac7278fa"
