identity = "5096dc08b83a82a8ec364e2b44c3cfc4a2098d41"
resolved_url = "https://newsletter.pragmaticengineer.com/feed"
title = "The Pragmatic Engineer"
site_url = "https://newsletter.pragmaticengineer.com/"
language = "en"
etag = 'W/"9ba61-hsK8aKF+5PEGO9hmpz2ZyofVTqE"'
body_hash = "86c2bc68a17ee4f1063bd866a73d99ca87d54ea1"
