identity = "5096dc08b83a82a8ec364e2b44c3cfc4a2098d41"
resolved_url = "https://newsletter.pragmaticengineer.com/feed"
title = "The Pragmatic Engineer"
site_url = "https://newsletter.pragmaticengineer.com/"
language = "en"
etag = 'W/"968ef-CgNBW6GjJcZQfcjqlF3teY+zUgk"'
body_hash = "0a03415ba1a325c6507dc8ea945ded798fb35209"
