identity = "5096dc08b83a82a8ec364e2b44c3cfc4a2098d41"
resolved_url = "https://newsletter.pragmaticengineer.com/feed"
title = "The Pragmatic Engineer"
site_url = "https://newsletter.pragmaticengineer.com/"
language = "en"
etag = 'W/"940c9-xvdPECJlZyncPBXHEkQioaDqKOk"'
body_hash = "c6f74f1022656729dc3c15c7124422a1a0ea28e9"
