url = "https://martinfowler.com/"
resolved_url = "https://martinfowler.com/feed.atom"
title = "Martin Fowler"
site_url = "https://martinfowler.com/"
etag = '"2f3e8-65a8736476f80"'
last_modified = "Wed, 02 Sep 2026 22:03:58 GMT"
body_hash = "e4cd39794061c18b4cce4bf8685a946a1a24017c"
