identity = "967f0735e1c09405151d45465cc49d387c67062f"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCrqM0Ym_NbK1fqeQG2VIohg"
title = "Tsoding Daily"
site_url = "https://www.youtube.com/channel/UCrqM0Ym_NbK1fqeQG2VIohg"
body_hash = "eece9303a921ec71c7d752e28ab856cbb9e5a067"
