identity = "967f0735e1c09405151d45465cc49d387c67062f"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCrqM0Ym_NbK1fqeQG2VIohg"
title = "Tsoding Daily"
site_url = "https://www.youtube.com/channel/UCrqM0Ym_NbK1fqeQG2VIohg"
body_hash = "262633abf4e45961096f7536a44e2c3296a1ec97"
