identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dlnxd20kc0nlddd-gzip"'
last_modified = "Thu, 24 Sep 2026 23:11:15 GMT"
body_hash = "b0f9ef5ab60c49c0a987e9c833d81f7cedd86796"
