identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dljm272ysohgeiv-gzip"'
last_modified = "Sat, 19 Sep 2026 21:29:12 GMT"
body_hash = "ae120f7842d4dda85ee1ab44b9654913f5b92077"
