identity = "5e7cf4436fafe7f5e16b3a7d9177507c02980a59"
resolved_url = "https://lobste.rs/top/1w.rss"
title = "Lobsters: Top Stories of the Past Week"
site_url = "https://lobste.rs/"
etag = '"dln1gkcjhrwldi6-gzip"'
last_modified = "Wed, 23 Sep 2026 22:11:15 GMT"
body_hash = "9c3cea2d9eb1412f960a633930dfb5110ea66b25"
