identity = "0e9e3e844ae95d070b9b324d95be38d3dcc8fa15"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCMOqf8ab-42UUQIdVoKwjlQ"
title = "Practical Engineering"
site_url = "https://www.youtube.com/channel/UCMOqf8ab-42UUQIdVoKwjlQ"
body_hash = "61eb4b9058621e6a53a08dd8f4cd3d89a2500e77"
