identity = "0e9e3e844ae95d070b9b324d95be38d3dcc8fa15"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCMOqf8ab-42UUQIdVoKwjlQ"
title = "Practical Engineering"
site_url = "https://www.youtube.com/channel/UCMOqf8ab-42UUQIdVoKwjlQ"
body_hash = "37890fb2b4f0a899c507be376dc632cca4684ef7"
