url = "https://aymericbeaumet.com/feed.xml"
title = "Aymeric Beaumet | Posts, Talks & Projects"
site_url = "https://aymericbeaumet.com/"
etag = '"dl2bubdimsxs1wgh-gzip"'
last_modified = "Sun, 30 Aug 2026 13:53:25 GMT"
body_hash = "b848ed54d9a1a77993aa57e7818c6eecece9af90"
