identity = "2c0d78b648bd40de13eb7fdcbf56bd9515d3eb2f"
resolved_url = "https://www.computerenhance.com/feed"
title = "Computer, Enhance!"
site_url = "https://www.computerenhance.com/"
language = "en"
etag = 'W/"19eb2-c8/DqE2DuENTN0zfI5wm44y9DDY"'
body_hash = "73cfc3a84d83b84353374cdf239c26e38cbd0c36"
