identity = "9067c77bad0f13be0af54dc963985b9cc52cdad9"
resolved_url = "https://microsoft.ai/feed/?post_type=new"
title = "Microsoft AI"
site_url = "https://microsoft.ai/"
etag = '"2e4eef41f08fba613a745a5e97117bc3"'
last_modified = "Sat, 05 Sep 2026 07:54:04 GMT"
body_hash = "0ed93963f4c2339b4f6db43bd6eccc6bc790800f"
