identity = "9067c77bad0f13be0af54dc963985b9cc52cdad9"
resolved_url = "https://microsoft.ai/feed/?post_type=new"
title = "Microsoft AI"
site_url = "https://microsoft.ai/"
language = "en-US"
etag = '"b082c39aebb315b3447dc5dafc21dc60"'
last_modified = "Sat, 19 Sep 2026 07:54:04 GMT"
body_hash = "10922c440bebf841ffd3b280498fbc31a1a54ec1"
