identity = "9067c77bad0f13be0af54dc963985b9cc52cdad9"
resolved_url = "https://microsoft.ai/feed/?post_type=new"
title = "Microsoft AI"
site_url = "https://microsoft.ai/"
etag = '"64c4c55bf918e4d421ca6d0d579cc8d2"'
last_modified = "Mon, 14 Sep 2026 13:19:14 GMT"
body_hash = "0907c47c24cf14ddb199bcf88a09ff54fa1d68a9"
