identity = "0089e13ed6b2659cdcddc9cb3d0c15d4411b0edd"
resolved_url = "https://blog.comma.ai/feed.xml"
title = "comma.ai blog"
site_url = "https://blog.comma.ai/"
etag = 'W/"6aaeb3b1-2829"'
last_modified = "Sat, 19 Sep 2026 16:09:21 GMT"
body_hash = "2752dbe3701fa3cbcb457c99cb7bcad2cd858a62"
