identity = "861041bfcffc224ba5721169f7dc9b22bfd78dac"
resolved_url = "https://cognition.com/blog"
title = "Blog | Cognition"
site_url = "https://cognition.com/"
etag = 'W/"75fdafc0abb6c34568082c2c0b44aeac"'
body_hash = "0abe3f8689edb493ed5bdcfa921d0041233359ba"
