identity = "5d1283f7a9c2743451bb5bce9ca988d7d1e3f8ba"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA"
title = "Computerphile"
site_url = "https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA"
body_hash = "2bcc3cdcf5919b201893d6656d638985606fb5a5"
