identity = "b4a8a36abc52a388c779d7523c8610e1d591470e"
resolved_url = "https://world.hey.com/dhh/feed.atom"
title = "David Heinemeier Hansson"
site_url = "https://world.hey.com/dhh"
language = "en-US"
etag = 'W/"0f37d50e3afb90168b82bfa9ea56df8a"'
body_hash = "800df2179358829ab665075f00418d5bc25f0249"
