identity = "49cc7c99f624dab263cb314a721ca6464e55e249"
resolved_url = "https://huggingface.co/blog/feed.xml"
title = "Hugging Face - Blog"
site_url = "https://huggingface.co/blog"
language = "en-US"
etag = 'W/"3e92e-2nwxTu2dU0iPamrCcntJAO0wMIQ"'
body_hash = "da7c314eed9d53488f6a6ac2727b4900ed303084"
