identity = "49cc7c99f624dab263cb314a721ca6464e55e249"
resolved_url = "https://huggingface.co/blog/feed.xml"
title = "Hugging Face - Blog"
site_url = "https://huggingface.co/blog"
etag = 'W/"3e1bf-BtuJ+UgdfyutafgENnCca2y0ZTM"'
body_hash = "06db89f9481d7f2bad69f80436709c6b6cb46533"
