identity = "e019b40360d3658a899dcfade2c6e5a90f9b4b16"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A"
title = "Numberphile"
site_url = "https://www.youtube.com/channel/UCoxcjq-8xIDTYp3uz647V5A"
body_hash = "8ed18a0220e7fc87ce01fa4500b42b89547cd2d9"
