identity = "1b20e3cefa53bb537c9111573807259bb431178f"
resolved_url = "https://blog.google/innovation-and-ai/technology/ai/"
title = "Official Google AI news and updates | Google Blog"
site_url = "https://blog.google/"
language = "en-US"
body_hash = "05424f8259b3cf076a337f395ad500e005d707d3"
