identity = "9d192594797042f63c7a6d1ca5f53ff5eb6ca32c"
resolved_url = "https://blog.google/innovation-and-ai/technology/ai/rss/"
title = "AI"
site_url = "https://blog.google/innovation-and-ai/technology/ai/"
body_hash = "5fd14eab4f51c6c6b19775b4df6e58035c59b0d6"
