identity = "9d192594797042f63c7a6d1ca5f53ff5eb6ca32c"
resolved_url = "https://blog.google/innovation-and-ai/technology/ai/rss/"
title = "AI"
site_url = "https://blog.google/innovation-and-ai/technology/ai/"
body_hash = "30dbd56f0fb7531f889d6db189a3f718669f4c93"
