identity = "4937019e2c7962265008a2d5dd33634f56608900"
resolved_url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
last_modified = "Fri, 04 Sep 2026 23:59:05 GMT"
body_hash = "7717aa16e8bce043032e60c6c4d5b67758b7229c"
