identity = "4937019e2c7962265008a2d5dd33634f56608900"
resolved_url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
last_modified = "Fri, 18 Sep 2026 14:36:41 GMT"
body_hash = "c3d97cbfbacdd2205b68d44a920a8ed0e65a7a7b"
