identity = "43ad7a1d4bd3f4476a20a01577a11053ae0d06a9"
resolved_url = "https://www.latent.space/feed"
title = "Latent.Space"
site_url = "https://www.latent.space/"
language = "en"
etag = 'W/"fb879-Ls/iE5tg+Si8vrXvFu8TmtzbmUM"'
body_hash = "2ecfe2139b60f928bcbeb5ef16ef139adcdb9943"
