url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
last_modified = "Wed, 02 Sep 2026 05:50:57 GMT"
body_hash = "20f7414387642f719f8f4de6955e5e043ac39a60"
