url = "https://simonwillison.net/"
resolved_url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
last_modified = "Fri, 04 Sep 2026 05:54:40 GMT"
body_hash = "196e570a47be63a90aa65759583ede8832136e14"
