url = "https://simonwillison.net/atom/everything/"
title = "Simon Willison's Weblog"
site_url = "http://simonwillison.net/"
last_modified = "Wed, 02 Sep 2026 14:16:42 GMT"
body_hash = "1b1c46173f847d85a43c7797250e6906327ac1c7"
