identity = "344390b868bc0d565841534dea06d59f47fd5082"
resolved_url = "https://feeds.acast.com/public/shows/le-rdv-tech"
title = "Le rendez-vous Tech - RDV Tech"
site_url = "https://www.rdvtech.fr/"
language = "fr"
etag = 'W/"djEuMi4wOjE3ODk0ODA4Mzk0MjE="'
body_hash = "7424f9f903979c0f75d26b985b9e52e842ad5277"
