identity = "344390b868bc0d565841534dea06d59f47fd5082"
resolved_url = "https://feeds.acast.com/public/shows/le-rdv-tech"
title = "Le rendez-vous Tech - RDV Tech"
site_url = "https://www.rdvtech.fr/"
language = "fr"
etag = 'W/"djEuMi4wOjE3OTAwODU2Mzk0ODg="'
body_hash = "dff6ac44381a3362c6a738ef4a4f7e4ad0b68b1d"
