identity = "5259f515efc0689105bb9ed219425ce71b7fa2a9"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA"
title = "Veritasium"
site_url = "https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA"
body_hash = "d65cdc6081c7ab6db61828f3785805f2e8f3fbcb"
