identity = "5259f515efc0689105bb9ed219425ce71b7fa2a9"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA"
title = "Veritasium"
site_url = "https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA"
body_hash = "16593f22c1c1748b602bb47f6918abe2e158dc8b"
