identity = "9a67e7de01fe2a7eed3c49cdf4dda9d8ccb17755"
resolved_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCSju5G2aFaWMqn-_0YBtq5A"
title = "Stand-up Maths"
site_url = "https://www.youtube.com/channel/UCSju5G2aFaWMqn-_0YBtq5A"
body_hash = "3a1a2a46066172150a385aa956be69d27eb9fca4"
