identity = "5f8802074b2cd8b27f08d5100d24d3d9d7510fc1"
resolved_url = "https://xkcd.com/atom.xml"
title = "xkcd.com"
site_url = "https://xkcd.com/"
language = "en"
etag = '"6ab1f1ea-8a0"'
body_hash = "50c82092a4e16cc9a9d1a19c7d6919f33ae7e442"
