identity = "5f8802074b2cd8b27f08d5100d24d3d9d7510fc1"
resolved_url = "https://xkcd.com/atom.xml"
title = "xkcd.com"
site_url = "https://xkcd.com/"
language = "en"
etag = '"6ab6a063-9e0"'
body_hash = "a6db8513adfa5f4f1eaa39dca0efa7a14536419f"
